export { default as Icons } from '../assets/icons.png'
export { default as CssIcon } from '../assets/css.svg'
export { default as HtmlIcon } from '../assets/html.svg'
export { default as ApiIcon } from '../assets/api.png'
export { default as CliIcon } from '../assets/command-line.png'
export { default as GitIcon } from '../assets/git.svg'
export { default as GithubIcon } from '../assets/github.svg'
export { default as JsIcon } from '../assets/js.svg'
export { default as ResponsiveIcon } from '../assets/responsive.png'
export { default as SassIcon } from '../assets/sass.svg'
export { default as ReactIcon } from '../assets/react.svg'
export { default as WacIcon } from '../assets/wac.png'
export { default as VscodeIcon } from '../assets/vscode.svg'
export { default as TailwindIcon } from '../assets/tailwind.svg'
export { default as plane } from '../assets/plane.jpg'

export { default as Work01 } from '../assets/works/work01.png'